# Packages for the cisreg project

# Normal, CRAN packages
install.packages("remotes")
install.packages("BiocManager")
install.packages("ape")
install.packages("countToFPKM")
install.packages("cowplot")
install.packages("data.table")
install.packages("dbscan")
install.packages("dplyr")
install.packages("effects")
install.packages("eulerr")
install.packages("ggdendro")
install.packages("ggplot2")
install.packages("ggpointdensity")
install.packages("ggrastr")
install.packages("ggrepel")
install.packages("ggvenn")
install.packages("gplots")
install.packages("gridExtra")
install.packages("igraph")
install.packages("knitr")
install.packages("Matrix")
install.packages("matrixStats")
install.packages("mclust")
install.packages("openxlsx")
install.packages("plyr")
install.packages("preprocessCore")
install.packages("readr")
install.packages("reshape2")
install.packages("signal")
install.packages("stringr")
install.packages("tibble")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("vegan")
install.packages("viridis")
install.packages("vroom")
install.packages("xlsx")

# Seurat, USE SPECIFIC VERSIONS
remotes::install_version("Seurat", version="4.3.0")
remotes::install_version("SeuratObject", version="4.1.3")

# Bioconductor packages
BiocManager::install("BiocParallel", update=FALSE)
BiocManager::install("circlize", update=FALSE)
BiocManager::install("cola", update=FALSE)
BiocManager::install("colorspace", update=FALSE)
BiocManager::install("ComplexHeatmap", update=FALSE)
BiocManager::install("DESeq2", update=FALSE)
BiocManager::install("EDASeq", update=FALSE)
BiocManager::install("edgeR", update=FALSE)
BiocManager::install("EnrichedHeatmap", update=FALSE)
BiocManager::install("ensembldb", update=FALSE)
BiocManager::install("GenomicFeatures", update=FALSE)
BiocManager::install("GenomicRanges", update=FALSE)
BiocManager::install("Gviz", update=FALSE)
BiocManager::install("harmony", update=FALSE)
BiocManager::install("limma", update=FALSE)
BiocManager::install("Mfuzz", update=FALSE)
BiocManager::install("RColorBrewer", update=FALSE)
BiocManager::install("rtracklayer", update=FALSE)
BiocManager::install("RUVSeq", update=FALSE)
BiocManager::install("seqQTL", update=FALSE)
BiocManager::install("Signac", update=FALSE)
BiocManager::install("topGO", update=FALSE)
BiocManager::install("tximport", update=FALSE)
BiocManager::install("WGCNA", update=FALSE)