---
title: 'Smed CisReg project 14: scATAC-seq marker analysis'
author: "Alberto Perez-Posada @apposada"
date: "17/4/2024"
output: html_document
---

```{r setup, include=FALSE}
dir <- '~/projects/smed_cisreg/'
fcha <- function(){ gsub("-","",Sys.Date()) }

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = dir)
options(scipen=999)
Sys.setenv(VROOM_CONNECTION_SIZE=5000072)
```

## About

In this markdown we will integrate the scATAC-seq data and the scRNA-seq data.

## Load libraries

```{r libraries, message=FALSE, warning=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
library(viridis)
library(ComplexHeatmap)
library(Seurat)
library(harmony)
library(colorspace)
library(Signac)
library(GenomicRanges)
library(rtracklayer)
library(ensembldb)
library(ggplot2)
library(igraph)
```

## Load functions

```{r load_functions}
source("code/r_code/functions/sourcefolder.R")

sourceFolder(
  "code/r_code/functions/", #change for definitive path once its final
  recursive = TRUE
  )
```

## Load Data
```{r}
smed_cisreg_scatac <- readRDS("outputs/rda/seurat_scatac/smed_cisreg_scATAC_consensus_identities.RDS")
```

## scATAC-seq markers

```{r}
smed_cisreg_scatac_markers <- 
  FindAllMarkers(
    smed_cisreg_scatac,
    assay = "peaks",
    only.pos = TRUE,
    min.pct = 0.1,
    logfc.threshold = 0.1
    )

smed_cisreg_scatac_markers_top <- 
  smed_cisreg_scatac_markers %>% 
  group_by(cluster) %>% 
  top_n(n = 150, wt = -log(p_val_adj)
  )

smed_cisreg_scatac_markers_top_viz <- 
  smed_cisreg_scatac_markers %>% 
  group_by(cluster) %>% 
  top_n(n = 10, wt = avg_log2FC)
```

Plotting all the markers:

```{r}
DefaultAssay(smed_cisreg_scatac) <- "peaks"

for (i in unique(smed_cisreg_scatac_markers_top_viz$cluster)){
  
  filt_clu_i <- smed_cisreg_scatac_markers_top_viz$cluster==i
  
  markers_clu_i <- 
    smed_cisreg_scatac_markers_top_viz$gene[filt_clu_i]

  featplot_clu_i <- 
    FeaturePlot(
      smed_cisreg_scatac,
      features = markers_clu_i,
      order = TRUE,
      combine = FALSE
      )
  
  featplot_clu_i <- 
    lapply(
      X = featplot_clu_i, 
      FUN = function(x) x + 
	        theme(plot.title = element_text(size = 5)) + 
			NoAxes()
      )
  
  p_clu_i <- CombinePlots(plots = featplot_clu_i)
  i_parsed <- gsub("/","_",i)
  pdf(
    file = paste0(
		"graphics/markers_scatac/smed_cisreg_scatac_cluster_",
		i_parsed,"_markers.pdf"),
    width= 10,
    height = 10
    )
  gridExtra::grid.arrange(
    p_clu_i, 
    bottom = paste0("cluster ",i)
    )
  dev.off()
}
```

### whole heatmap

Here a heatmap of all the markers:

```{r heatmap of markers}
DefaultAssay(smed_cisreg_scatac) <- "peaks"
smed_cisreg_scatac_scaled <- ScaleData(smed_cisreg_scatac, features = rownames(smed_cisreg_scatac))

atac_pal <-
  setNames(
    unique(smed_cisreg_scatac_ctypes$broadcol),
    unique(smed_cisreg_scatac_ctypes$broadtype)
    )

pdf("graphics/scatac_plots/smed_cisreg_scatac_markers_heatmap.pdf", height = 6, width = 16)
DoHeatmap(
  smed_cisreg_scatac_scaled, 
  features = smed_cisreg_scatac_markers_top_viz$gene,
  group.colors = atac_pal
    )+ 
  scale_fill_viridis() + 
  NoLegend() + 
  ggtitle ("Markers Heatmap") + theme(text = element_text(size = 5))
dev.off()
```

## scATAC-seq markers (from GeneActivity)

```{r}
smed_cisreg_scatac_markers_geneAct <- FindAllMarkers(smed_cisreg_scatac, assay = "RNA",only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.1)
smed_cisreg_scatac_markers_geneAct_top <- smed_cisreg_scatac_markers_geneAct %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
```

Plotting all the markers:

```{r}
DefaultAssay(smed_cisreg_scatac) <- "RNA"

for (i in unique(smed_cisreg_scatac_markers_geneAct_top$cluster)){
  
  filt_clu_i <- smed_cisreg_scatac_markers_geneAct_top$cluster==i
  
  markers_clu_i <- 
    smed_cisreg_scatac_markers_geneAct_top$gene[filt_clu_i]

  featplot_clu_i <- 
    FeaturePlot(
      smed_cisreg_scatac,
      features = markers_clu_i,
      order = TRUE,
      combine = FALSE
      )
  
  featplot_clu_i <- 
    lapply(
      X = featplot_clu_i, 
      FUN = function(x) x + theme(plot.title = element_text(size = 5)) + NoAxes()
      )
  
  p_clu_i <- CombinePlots(plots = featplot_clu_i)
  i_parsed <- gsub("/","_",i)
  pdf(
    file = paste0("graphics/markers_scatac/smed_cisreg_scatac_cluster_",i_parsed,"_geneActivity_markers.pdf"),
    width= 10,
    height = 10
    )
  gridExtra::grid.arrange(
    p_clu_i, 
    bottom = paste0("cluster ",i)
    )
  dev.off()
}
```

## Saving everything

```{r}
save(
  smed_peaks,
  file = "outputs/rda/scatac_peaks.rda"
)

write.table(
  smed_peaks,
  file = "~/projects/smed_cisreg/outputs/scatac/seurat_outputs/smed_peaks_with_names.bed",
  row.names = FALSE,
  col.names = FALSE,
  quote = FALSE,
  sep = "\t"
  )

save(
  smed_cisreg_scatac_markers,
  smed_cisreg_scatac_markers_top,
  smed_cisreg_scatac_markers_viz,
  smed_cisreg_scatac_markers_geneAct,
  smed_cisreg_scatac_markers_geneAct_top,
  file = "outputs/rda/scatac_markers.rda"
)

```